config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  } 

  root to: "home#index"

  namespace :user, path: '/' do
    get '/profile', to: "dashboard#index", as: 'profile'

    resources :diets, only: [:new, :create, :show] do
      resource :diet_progress, only: [ :create ], as: 'progress'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :diets, dependent: :destroy

  validates :name,  presence: true

  validates :email,
    presence: true, 
    uniqueness: { case_sensitive: false },
    format: { with: Devise.email_regexp }

  validates :password, presence: true

  validates :height, presence: true, numericality: { only_integer: true }

  enum role: { admin: 'admin' , member: 'member' }
end

app/controllers/user/dashboard_controller.rb
class User::DashboardController < ApplicationController
  layout 'app'

  before_action :authenticate_user!

  def index
    @user = current_user

    @diets = 
      @user
      .diets
      .includes(:diet_progress)
      .order(created_at: :desc)
      .page params[:page]

    @current_diet = @diets.first

    @date_progress = DietProgress.new

    unless @current_diet.nil?
      @chart_data = {
        weight_data: @current_diet.diet_progress.map{|e| e.weight / 1000.0},
        goal: @current_diet.weight_goal / 1000.0,
        date_array: @current_diet.diet_progress.map{|e| 
          e.weighing_date.strftime("%d/%m/%y") }
      }
    end
    
  end
end

app/controllers/user/diets_controller.rb
class User::DietsController < ApplicationController
  layout 'app'
  
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::JavaScriptHelper
  
  before_action :authenticate_user!
  before_action :set_user, only: [:new, :show]

  def show
    @diet = @user.diets.find(params[:id])
  end

  def new
    @diet = Diet.new
  end

  def create    
    @diet = Diet.new(diet_params)
    @diet.user = current_user

    if @diet.valid?
      @diet.save

      flash[:notice] = "Diet created successfully"

      redirect_to user_profile_path, stataus: :created
    else
      flash[:alert] = "Diet could not be created"
      render 'new'
    end
  end

  private
  def diet_params
    params_hash = params.require(:diet).
      permit([:ending_date, :weight_goal, :current_weight])

    params_hash["starting_date"] = Date.today
    
    ["weight_goal", "current_weight"].each do |e|
      params_hash[e].gsub!(/\D/, '')
    end

    params_hash
  end

  def set_user
    @user = current_user
  end
end

app/controllers/user/diets_progress_controller.rb
class User::DietsProgressController < ApplicationController
  before_action :authenticate_user!
  
  def create
    respond_to do |format|
      format.js {
        @diet = current_user
          .diets
          .find(params["diet_id"])

        params_hash = diet_progress_params

        @diet_progress = DietProgress.
          where({ 
            weighing_date: params_hash["weighing_date"], 
            diet_id: @diet.id })
          .first_or_initialize
        
        @diet_progress.assign_attributes( params_hash )  

        if @diet_progress.valid?
          @diet_progress.save
          @weight_data = @diet.diet_progress.map{|e| e.weight / 1000.0}
          @date_array = @diet.diet_progress.map{|e| 
            e.weighing_date.strftime("%d/%m/%y") }

          render file: 'shared/on_date_progress_success'
        else 
            render file: 'shared/on_date_progress_failure'
        end 
      }
    end
  end

  private
  
  def diet_progress_params
    params_hash = params.require(:diet_progress).
      permit([:weighing_date, :weight])

    params_hash["weight"].gsub!(/\D/, '')

    params_hash
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  layout 'app'
  include ActionView::Helpers::SanitizeHelper
  include ActionView::Helpers::JavaScriptHelper

  def create
    @user = User.new(user_params)

    if @user.valid? 
      @user.save
      sign_in @user
      flash[ :notice ] = I18n.t 'devise.registrations.signed_up'
      redirect_to user_profile_path 
    else
      flash[ :alert ] = I18n.t 'errors.messages.not_saved.one', resource: User
      render 'new'
    end
  end

  protected
  def user_params
    params_hash = params.require(:user).permit([:name, :email, :password, :height])
    sanitize_inputs params_hash
  end

  def sanitize_inputs(params)
    fields = ['name', 'email'].freeze

    fields.each do |field|
      params[field] = escape_javascript( sanitize params[field] )
    end
    
    return params
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  layout 'app'
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    redirect_to user_profile_path
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/user/dashboard/index.html.erb
<div class="spaced-elements content">
  <h4>Hello, <%= @user.name %></h4>

  <% unless @current_diet.nil? %>
    <a class="waves-effect waves-light btn modal-trigger" href="#modal1">
      Register Weight
    </a>    
  <% end %>
</div>

<div class="content">

  <% if @current_diet.nil?  %>    
    <h4> You haven't start any diet yet, click     
      <%= link_to('here', new_user_diet_path ) %> to do it </h4>
  <% else %>

    <div>
      <canvas id="chart_frame" width="100%" height="50"></canvas>
    </div>
  <% end %> 
  
</div>


<div class="content">
  <p>Hey <%= @user.name %>, here's your progress, Keep going!</p>
</div>


<% unless @current_diet.nil? %>
  <div class="spaced-elements content">
    <%= link_to 'More Details', user_diet_path(id: @current_diet.id), 
    class: "waves-effect waves-light btn" %>
    
    <%= paginate @diets %>
  </div>  
<% end %>


<% unless @current_diet.nil? %>
  <div id="modal1" class="modal">
    <div class="modal-content" style="height: 50vh;" >
      <h4>Please inform your weight</h4>
      <%= render(
        partial: 'user/diet_progress/form', 
        locals: { resource: @current_diet, object: @date_progress }
      ) %>
    </div>
    <div class="modal-footer">
      <a href="#!" 
        class="modal-action modal-close waves-effect waves-green btn-flat">
        
        Close
      </a>
    </div>
  </div>

<% end %>

<script>
  var chart_data = []
  var goal = 0
  var date_array = []

  <% unless @current_diet.nil? %>      
    var chart_data = <%= @chart_data[:weight_data] %>
    var goal = <%= @chart_data[:goal] %>
    var goal_data = chart_data.map( () => goal ) 
    var date_array = <%= raw @chart_data[:date_array] %>

    var min_y = Math.floor(Math.min(...chart_data, ...goal_data) - 1)
    var max_y = Math.ceil(Math.max(...chart_data, ...goal_data) + 1)

    chart = initLineChart(
      "chart_frame", 
      chart_data, 
      "Weight", 
      date_array, 
      goal_data,
      min_y,
      max_y);
  <% end %>

  
  $(document).ready(() => {
    $('.modal').modal();
    $('.weight').mask('000(kg) 000(g)',  {reverse: true});    

    setAnotationPlugin()

    if ( $('.datepicker').length > 0 ) {
      ( $('.datepicker').pickadate({
        format: 'mmmm d, yyyy',
      }) )
    }
  });


</script>